config/routes.rb
Rails.application.routes.draw do
  root to: 'application#welcome'
  get '/signup' => 'contributors#new'
  post '/signup' => 'contributors#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  resources :contributors
  
  resources :recipes
  
  resources :recipe_creators do 
    resources :recipes, only: [:index, :show, :new, :create] 
  end 
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contributor.rb
class Contributor < ApplicationRecord
    has_many :recipes
    has_many :recipe_creators, through: :recipes

    validates :name, presence: true
    validates :email, uniqueness: true, presence: true
    
    has_secure_password

    def self.contribs_recipes
        joins(:recipes).group('contributors.name')
    end

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :contributor
  belongs_to :recipe_creator
  accepts_nested_attributes_for :recipe_creator

  validates :title, :ingredients, :directions, :recipe_creator, presence: :true

  validate :only_one_recipe_for_recipe_creator

    def only_one_recipe_for_recipe_creator
        #if contributor creates a new recipe creator when creating a new recipe , show error
        if Recipe.find_by(title: title, recipe_creator_id: recipe_creator_id)
            errors.add(:title, "already exists in this Family Member's Recipe Box")
        end
    end

   
    
    def recipe_creator_attributes=(attributes)
      self.recipe_creator = RecipeCreator.find_or_create_by(attributes) if !attributes['name'].empty?
      self.recipe_creator
    end

  def new
  end

end

app/models/recipe_creator.rb
class RecipeCreator < ApplicationRecord
    has_many :recipes
    has_many :contributors, through: :recipes

    
    validates :name, presence: true
    validates :phone_number, uniqueness: true 
    
        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper

    def welcome
        if !logged_in?
            redirect_to login_path
        end
        
    end 

end

app/controllers/contributors_controller.rb
class ContributorsController < ApplicationController

    def index
        @contributors = Contributor.contribs_recipes
    end
    
    
    def new # render a signup form
        if !logged_in?
            @contributor = Contributor.new
            render action: "new", layout: false
        else 
            redirect_to recipes_path
        end
    end 

    def create
        @contributor = Contributor.new(contributor_params)
        if @contributor.save
            session[:contributor_id] = @contributor.id
            redirect_to recipes_path
        else
            render :new
        end
    end



    



    private

    def contributor_params
        params.require(:contributor).permit(:name, :email, :password)
    end


end

app/controllers/recipe_creators_controller.rb
class RecipeCreatorsController < ApplicationController

   


    def new
        @recipe_creator = RecipeCreator.new
    end

    
    def index
        @recipe_creators = RecipeCreator.all
    end


    def show
        @recipe_creator = RecipeCreator.find_by(id:params[:id])
        
    end


    
    

    private 

      def recipe_creator_params
        params.require(:recipe_creator).permit(:name, :phone_number, :secret_ingredient, :recipe_id)
      end 
    
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :set_recipe, except: [:index, :new, :create]
    before_action :set_recipe_creator, only: [:index, :new, :create]


    def index
        if params[:recipe_creator_id] 
            @recipes = @recipe_creator.recipes 
            
        else
            @recipes = Recipe.all
        end
    end

   
    def new
        if params[:recipe_creator_id]
            @recipe = @recipe_creator.recipes.build  #for the _attributes- doesnt inter. with the writer method/ tell eah other about each other
        else
            @recipe = Recipe.new
            @recipe.build_recipe_creator
        end
    end


    def create 
        if params[:recipe_creator_id]
          @recipe = @recipe_creator.recipes.build(recipe_params)
          @recipe.contributor_id = session[:contributor_id]
        else 
          @recipe = Recipe.new(recipe_params)
          @recipe.contributor_id = session[:contributor_id]
        end
    
        if @recipe.save
            redirect_to recipe_path(@recipe)
            
        else 
          render :new
        end 
    end
   

    def show  
    end


    def edit  
    end


    def update
        if @recipe.update(recipe_params)
            redirect_to recipe_path(@recipe)
        end
    end


    def destroy
        @recipe.destroy
        redirect_to recipes_path
    end

    

    private

    def recipe_params
        params.require(:recipe).permit(:title, :ingredients, :directions, :contributor_id, :recipe_creator_id, recipe_creator_attributes: [:name, :phone_number, :secret_ingredient])
    end

    def set_recipe
        @recipe = Recipe.find_by_id(params[:id])
    end 

    def set_recipe_creator
        @recipe_creator = RecipeCreator.find_by(id: params[:recipe_creator_id])
    end
end
 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new # render the login form 
      render action: "new", layout: false
        if logged_in?
            redirect_to recipes_path   
        end
    end

    def create #processing login form
        contributor = Contributor.find_by(email: params[:email])
        if contributor && contributor.authenticate(params[:password])
            session[:contributor_id] = contributor.id
            redirect_to recipes_path
        else
            render :new
        end
         
    end

    def destroy #logout
        session.delete :contributor_id
        redirect_to login_path
    end

    def omniauth 
        contributor = Contributor.find_or_create_by(uid: request.env['omniauth.auth'][:uid], provider: request.env['omniauth.auth'][:provider]) do |c|
          c.name = request.env['omniauth.auth'][:info][:first_name]
          c.email = request.env['omniauth.auth'][:info][:email]
          c.password = SecureRandom.hex(15)
        end 
        if contributor.valid?
          session[:contributor_id] = contributor.id # log them 
          redirect_to recipes_path
        else
          redirect_to login_path 
        end 
      end 
end

app/helpers/application_helper.rb
module ApplicationHelper

    def current_user #memoization
        @current_user ||= Contributor.find_by(id: session[:contributor_id])

    end

    def logged_in?
        current_user
    end
end

app/helpers/contributors_helper.rb
module ContributorsHelper
end

app/helpers/recipe_creators_helper.rb
module RecipeCreatorsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/application/welcome.html.erb
<h1> Welcome to Family Recipe Box</h1>

app/views/contributors/index.html.erb
<h1> Family Recipe Box Contributors </h1>

<% @contributors.each do |contributor| %>
    <h4><%= contributor.name %></h4>
       <% contributor.recipes.each do |recipe| %>
        <li> <%= link_to recipe.title, recipe_path(recipe) %> </li>
    <% end %>
    <br>
    <br>
<% end %>

    

app/views/contributors/new.html.erb
<h1> Signup </h1>
<%= render partial: 'layouts/errors',locals: {object: @contributor} %>

<%= form_for(@contributor) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email%>
    <%= f.email_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.submit "Sign up" %>
<% end %>

<h3>Or Signup with Google:</h3>

<%= button_to 'Google', '/auth/google_oauth2' %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FamilyRecipeBox</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <br>
    <%= link_to "Recipe Box", recipes_path %> | 
    <%= link_to "Add New Recipe", new_recipe_path %> | 
    <%= link_to "Family Recipe Creators", recipe_creators_path %> |
    <%= link_to "Family Recipe Box Contributors", contributors_path %>

    <br>
    <br>
    <%= button_to 'Logout', logout_path %>
      <%= yield %>
  </body>
</html>

app/views/recipe_creators/index.html.erb
<h1> Family Recipe Creators </h1>

<% @recipe_creators.each do |recipe_creator| %>
    <li> <%= link_to recipe_creator.name, recipe_creator_recipes_path(recipe_creator) %> <br> </li> 
<%end%>

app/views/recipes/_form.html.erb
<%= f.label :title %> <br>
<%= f.text_field :title %><br>
<%= f.label :ingredients%> <br>
<%= f.text_area :ingredients %><br>
<%= f.label :directions %> <br>
<%= f.text_area :directions %>
<%if @recipe_creator %>
<%= f.hidden_field :recipe_creator_id, value: @recipe_creator.id %>
<% else %>

<h2> Recipe Created by: </h2>

<%= f.collection_select(:recipe_creator_id, RecipeCreator.all, :id, :name, {:prompt => 'Select Recipe Creator'}) %>

<h5> Or Add a New Family Member </h5>
    <%= f.fields_for :recipe_creator do |rc| %>
        <%= rc.label :name %>
        <%= rc.text_field :name %>
        <%= rc.label :phone_number %>
        <%= rc.telephone_field :phone_number %><br>
        <br>
        Do they like to keep 
        <%= rc.label :secret_ingredient%>s ?
        <%= rc.text_field :secret_ingredient %><br>
        
    <% end %>
<%end %>
<br>
<%= f.submit %>

app/views/recipes/edit.html.erb
<h1> Edit Recipe </h1>

<%= form_for([@recipe_creator, @recipe]) do |f| %>
    <%=render partial: "form", locals: {f: f} %>
<% end %>

app/views/recipes/index.html.erb
<br>
<% if @recipe_creator %>
        <h1><%= @recipe_creator.name %>'s Recipe Box </h1> <br>
        <%= link_to "Add a New Recipe", new_recipe_creator_recipe_path %> <br>   
<% else %>
<h1> Family Recipe Box </h1>
<% end %>

        <% @recipes.each do |r| %><br>
            <h3><%= link_to r.title, recipe_path(r) %><h3>
            Created by: <%= r.recipe_creator.name %> <br>
            Added by: <%= r.contributor.name %> 
            <br>
            <br>
        <% end %> 
  

   

    
    
    

    

app/views/recipes/new.html.erb
<h1> Add a New Recipe </h1>

<%=render partial: 'layouts/errors',locals: {object: @recipe} %>

<%= form_for([@recipes, @recipe]) do |f| %>
    <%=render partial: "form", locals: {f: f} %>
<% end %>

app/views/recipes/show.html.erb
<h1><%= @recipe.recipe_creator.name %>'s <%= @recipe.title %></h1>

Ingredients: <br>
<%= @recipe.ingredients %> <br>
<br>
Directions: <br>
<%= @recipe.directions %>
<br>
<br>
<br>
Added by: <%= @recipe.contributor.name %> <br>
Created by: <%= @recipe.recipe_creator.name %> <br>



<% if @recipe.recipe_creator.secret_ingredient == "yes" %>
    <h4><%=@recipe.recipe_creator.name %> is usually keeping a secret ingredient! Call them to see if they'll share it with you. Good luck! </h4>
    Contact: <%= @recipe.recipe_creator.phone_number %> <br>
<% end %>
<br>
<br>
<%= link_to'Delete Recipe', recipe_path(@recipe), method: 'delete' %> <br>
<%= link_to 'Edit Recipe', edit_recipe_path(@recipe) %>


 